workflows:
  flutter-android:
    name: Flutter Android APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Flutter version
        script: flutter --version
      - name: Create Android project if missing
        script: |
          if [ ! -d "android" ]; then
            flutter create --platforms=android .
          fi
      - name: Pub get
        script: flutter pub get
      - name: Build debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
